Switch to not existed responder
chausovSurfStudio/TextFieldsCatalog pull request #100
Opened 2020-11-24 20:35 UTC by chausovSurfStudio

Рассказываю причины произошедшего.

Был баг. Заходим на экран - там куча полей (форма обратной связи). Начинаем по стрелкам в тулбаре переключаться на следующее поле, потом на следующее, и тд. До конца доходим. Затем идем в обратную сторону. Пару раз переход к предыдущему полю работает.
На подскроллы работают таким образом, что со временем контент таблицы устаканивается таким образом, что ячейка с активным полем ввода находится четко сверху. Пытаемся переключиться на предыдущее - и не работает. Что не удивительно, так как ячейки предыдущего поля ввода на экране нет -> система не знает что делать. Но при этом она понимает, что firstResponder-ом стало другое поле. И если смахнуть экран (форма обратной связи - смахиваемая модалка) - то клавиатура останется висеть) и переход к следующему полю ввода кажется перестанет работать, но это уже точно не помню

Вот такие пироги. Как я вижу решение:
* сначала вот эта вот фича, что в ПРе. Фактически - мы не даем переключиться на поле ввода, если оно не находится в данный момент на экране. Чтобы клавиатура не оставалась в таких кейсах висеть
* а потом уже поправить подскроллы, чтобы в целом избежать таких кейсов

На проекте протестил, вроде робит

2020-11-27 07:32 UTC, Alelenka requested changes

2020-11-27 07:32 UTC, Alelenka commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +            previousInput?.becomeFirstResponder()
Я кажется что-то упускаю, но мы сюда можем придти же и из `switchToNextInput()` - в else всегда `previousInput?.becomeFirstResponder()`, то есть не будет ли вернее написать `responder?.becomeFirstResponder()`
+ такой же вопрос и для `UnderlinedTextView`

2020-11-27 10:28 UTC, chausovSurfStudio commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +            previousInput?.becomeFirstResponder()
🔥 
справедливо
копипаст(

2020-11-30 12:38 UTC, Alelenka approved these changes

2020-12-01 07:46 UTC, merged