Возможность выключать несколько действий редактирования
chausovSurfStudio/TextFieldsCatalog pull request #121
Opened 2021-08-04 06:13 UTC by ngagarinov

- Добавил интерфейс для выключения действий редактирования для UITextView и UITextField
- Пришлось добавить новое базовое Text View, сделал его по аналогии с Text Field

2021-08-10 06:53 UTC, chausovSurfStudio requested changes
* направь ПР dev/version-1 еще, я там до релиза изменения собираю в кучку)
* правильно понимаю, что если затянуть эти изменения и не обновить класс textView в ксибе на новый - то креш будет? давай допиши про это в ПР, и про то что `pasteActionEnabled` ушел - я потом к каждой версии прикладываю ссылки на ПРы, поэтому лучше когда у них полное развернутое описание со всеми произошедшими изменения и действиями, необходимыми к корректной миграции

2021-08-10 06:53 UTC, chausovSurfStudio commented on TextFieldsCatalog/Library/Utils/StandardEditActions.swift
> +        return [.cut, .copy, .paste, .selectAll, .delete]
`select` нет, так задумано?

2021-08-10 06:53 UTC, chausovSurfStudio commented on TextFieldsCatalog/Library/BaseClasses/InnerTextView.swift
> +    private var editActions: [StandardEditActions: Bool]? = nil
задумка вроде окъ, но на мой взгляд немного переусложнено) есть словарь, в котором можно каждому ключу true/false задать, но в коде задается только false - так может и не нужен словарь?

сделать тогда что-то в духе (` = nil необязательно вроде`)
```swift
private var disabledActions: [StandardEditActions]?
```

тогда это упроститься до одной строчки
```swift
    func disableEditActions(only actions: [StandardEditActions]?) {
        disabledActions = actions
    }
```

да и здесь кажется попроще станет
```swift
    override public func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool {
        guard disabledActions?.first(where: { $0.selector == action }) != nil else {
            return super.canPerformAction(action, withSender: sender)
        }
        return false
    }
```

2021-08-10 06:53 UTC, chausovSurfStudio commented on TextFieldsCatalog/Library/BaseClasses/InnerTextView.swift
> +    private var editActions: [StandardEditActions: Bool]? = nil
в textField соответственно то же самое

2021-08-17 14:11 UTC, ngagarinov commented on TextFieldsCatalog/Library/Utils/StandardEditActions.swift
> +        return [.cut, .copy, .paste, .selectAll, .delete]
Косяк, поправил

2021-08-17 14:18 UTC, ngagarinov commented on TextFieldsCatalog/Library/BaseClasses/InnerTextView.swift
> +    private var editActions: [StandardEditActions: Bool]? = nil
Так лучше, да, поправил

2021-08-18 16:45 UTC, chausovSurfStudio approved these changes

2021-08-18 16:45 UTC, merged